-- CRIANDO A TABELA DE CLIENTE PARA PRODU플O
select TOP 10 * from [dbo].[TB_CG_OLIST_COSTUMER]

CREATE TABLE TB_ACT_OLIST_COSTUMER
(
CUSTOMER_ID NVARCHAR(150),
CUSTOMER_UNIQUE_ID NVARCHAR(150),
CUSTOMER_ZIP_CODE_PREFIX NVARCHAR(15),
CUSTOMER_CITY NVARCHAR(100),
CUSTOMER_STATE CHAR(2),
)

INSERT INTO TB_ACT_OLIST_COSTUMER
SELECT * FROM [dbo].[TB_CG_OLIST_COSTUMER]

SELECT * FROM TB_ACT_OLIST_COSTUMER



-- CRIANDO A TABELA DE LOCALIZA플O PARA PRODU플O
select TOP 10 * from [dbo].[TB_CG_OLIST_GEOLOCATION]

CREATE TABLE TB_ACT_OLIST_GEOLOCATION
(
GEOLOCATION_ZIP_CODE_PREFIX NVARCHAR(15),
GEOLOCATION_LAT NVARCHAR(100),
GEOLOCATION_LNG NVARCHAR(100),
GEOLOCATION_CITY NVARCHAR(100),
GEOLOCATION_STATE CHAR(2),
)

INSERT INTO TB_ACT_OLIST_GEOLOCATION
SELECT * FROM [dbo].[TB_CG_OLIST_GEOLOCATION]

SELECT * FROM TB_ACT_OLIST_GEOLOCATION




-- CRIANDO A TABELA DE ORDENS DE ITENS PARA PRODU플O
SELECT TOP 10 * from [dbo].[TB_CG_OLIST_ORDER_ITEMS]

UPDATE [dbo].[TB_CG_OLIST_ORDER_ITEMS] SET shipping_limit_date = NULL
WHERE shipping_limit_date = ''

CREATE TABLE TB_ACT_OLIST_ORDER_ITEMS
(
ORDER_ID NVARCHAR(150),
ORDER_ITEM_ID CHAR(3),
PRODUCT_ID NVARCHAR(150),
SELLER_ID NVARCHAR(150),
SHIPPING_LIMIT_DATE DATETIME,
PRICE NVARCHAR(50),
FREIGHT_VALUE NVARCHAR(50)
)

INSERT INTO TB_ACT_OLIST_ORDER_ITEMS
SELECT * FROM [dbo].[TB_CG_OLIST_ORDER_ITEMS]


SELECT * FROM TB_ACT_OLIST_ORDER_ITEMS


-- TABELA DE ORDENS DE PAGAMENTO PARA PRODU플O
select TOP 100 * from [dbo].[TB_CG_OLIST_ORDER_PAYMENTS]

CREATE TABLE TB_ACT_OLIST_ORDER_PAYMENTS
(
ORDER_ID NVARCHAR(150),
PAYMENT_SEQUENTIAL CHAR(3),
PAYMENT_TYPE NVARCHAR(100),
PAYMENT_INSTALLMENTS CHAR(2),
PAYMENT_VALUE NVARCHAR(50)
)

INSERT INTO TB_ACT_OLIST_ORDER_PAYMENTS
SELECT * FROM [dbo].[TB_CG_OLIST_ORDER_PAYMENTS]

SELECT * FROM TB_ACT_OLIST_ORDER_PAYMENTS




-- TABELA DE ORDENS DE AVALIA합ES DO PRODUTO PARA PRODU플O
select TOP 10 * from [dbo].[TB_CG_OLIST_ORDER_REVIEWS]

UPDATE [dbo].[TB_CG_OLIST_ORDER_REVIEWS] SET review_creation_date = NULL
WHERE review_creation_date = ''

CREATE TABLE TB_ACT_OLIST_ORDER_REVIEWS
(
REVIEW_ID NVARCHAR(150),
ORDER_ID NVARCHAR(100),
REVIEW_SCORE CHAR(1),
REVIEW_COMMENT_TITLE NVARCHAR(100),
REVIEW_COMMENT_MESSAGE NVARCHAR (4000),
REVIEW_CREATION_DATE DATETIME,
REVIEW_ANSWER_TIMESTAMP DATETIME,
)

INSERT INTO TB_ACT_OLIST_ORDER_REVIEWS 
SELECT * FROM [dbo].[TB_CG_OLIST_ORDER_REVIEWS];

SELECT * FROM TB_ACT_OLIST_ORDER_REVIEWS




-- CRIANDO A TABELA DE ORDENS PARA PRODU플O
select TOP 10 * from [dbo].[TB_CG_OLIST_ORDERS]



CREATE TABLE TB_ACT_OLIST_ORDERS
(
ORDER_ID NVARCHAR(100),
CUSTOMER_ID NVARCHAR(150),
ORDER_STATUS NVARCHAR(30),
ORDER_PURCHASE_TIMESTAMP DATETIME,
ORDER_APPROVED_AT DATETIME,
ORDER_DELIVERED_CARRIER_DATE DATETIME,
ORDER_DELIVERED_CUSTOMER_DATE DATETIME,
ORDER_ESTIMATED_DELIVERY_DATE DATETIME
)

INSERT INTO TB_ACT_OLIST_ORDERS
SELECT * FROM [dbo].[TB_CG_OLIST_ORDERS];

SELECT * FROM TB_ACT_OLIST_ORDERS







-- CRIANDO A TABELA DE CATEGORIA DOS PRODUTOS PARA PRODU플O
select TOP 10 * from [dbo].[TB_CG_OLIST_PRODUCT_CATEGORY]



CREATE TABLE TB_ACT_PRODUCT_CATEGORY
(
PRODUCT_CATEGORY_NAME NVARCHAR(100),
PRODUCT_CATEGORY_NAME_ENGLISH NVARCHAR(100)
)

INSERT INTO TB_ACT_PRODUCT_CATEGORY
SELECT * FROM [dbo].[TB_CG_OLIST_PRODUCT_CATEGORY];

SELECT * FROM TB_ACT_PRODUCT_CATEGORY




-- CRIANDO A TABELA DOS PRODUTOS PARA PRODU플O
select * from [dbo].[TB_CG_OLIST_PRODUCTS]


CREATE TABLE TB_ACT_PRODUCTS
(
PRODUCT_ID NVARCHAR(150),
PRODUCT_CATEGORY_NOME NVARCHAR(100),
PRODUCT_NOME_LENGHT INT,
PRODUCT_DESCRIPTION_LENGHT INT,
PRODUCT_PHOTOS_QTY INT,
PRODUCT_WEIGHT_G INT,
PRODUCT_LENGTH_CM INT,
PRODUCT_HEIGHT_CM INT,
PRODUCT_WIDTH_CM INT,
)

INSERT INTO TB_ACT_PRODUCTS
SELECT * FROM [dbo].[TB_CG_OLIST_PRODUCTS];

SELECT * FROM TB_ACT_PRODUCTS





-- CRIANDO A TABELA DOS VENDEDORES PARA PRODU플O
select * from [dbo].[TB_CG_OLIST_SELLERS]


CREATE TABLE TB_ACT_SELLERS
(
SELLER_ID NVARCHAR(150),
SELLER_ZIP_CODE_PREFIX INT,
SELLER_CITY NVARCHAR(150),
SELLER_STATE CHAR(2),
)

INSERT INTO TB_ACT_SELLERS
SELECT * FROM [dbo].[TB_CG_OLIST_SELLERS];

SELECT * FROM TB_ACT_SELLERS

