SELECT * FROM [dbo].[TB_ACT_OLIST_COSTUMER];


--CRIANDO UMA VIEW
CREATE VIEW VW_PEDIDOS_POR_CLIENTE 
AS

SELECT O.*, C.CUSTOMER_CITY, C.CUSTOMER_STATE
FROM [dbo].[TB_ACT_OLIST_ORDERS] AS O
INNER JOIN [dbo].[TB_ACT_OLIST_COSTUMER] AS C
ON O.CUSTOMER_ID = C.CUSTOMER_ID 


SELECT * FROM VW_PEDIDOS_POR_CLIENTE


--ALTERANDO VIEW COM UM REQUISITO
ALTER VIEW VW_PEDIDOS_POR_CLIENTE 
AS

SELECT O.*, C.CUSTOMER_CITY, C.CUSTOMER_STATE
FROM [dbo].[TB_ACT_OLIST_ORDERS] AS O
INNER JOIN [dbo].[TB_ACT_OLIST_COSTUMER] AS C
ON O.CUSTOMER_ID = C.CUSTOMER_ID
WHERE ORDER_STATUS = 'DELIVERED'

SELECT * FROM VW_PEDIDOS_POR_CLIENTE


SELECT * FROM [dbo].[TB_ACT_OLIST_GEOLOCATION]